### ISSUE TITLE
There is an alignment issue with text going over the lighthouse.

### ISSUE THREAD

**Issue by briankidd9design** [IndigoSlam/4_GIT_ABOUT_IT#18]
We need to make sure the alignments are better for the words by the lighthouse and also in the water.

**Comment by MikeTheGreat** [comment]
Hi Brian,
Would you mind re-writing this so it's clear, exactly, what the issue is?  The Spolsky article recommended including:
1. Steps to reproduce,
2. What you expected to see, and
3. What you saw instead.

For something like this it might not be bad to include a screenshot, too.
Thanks!
--Mike

**Comment by briankidd9design** [comment]
Hi Mike and all.
1. Click on About
2.I expected to see the text to be easily readable away from the lighthouse.
3. The text overlaps the lighthouse a bit. 
Screenshot below. 
![image](https://cloud.githubusercontent.com/assets/9359143/15407802/b82d9d7e-1dc1-11e6-9172-4cf1552f0605.png)

**Comment by MikeTheGreat** [comment]
@briankidd9design  - excellent description!
