### ISSUE TITLE
"Back to List" link does not work after the game has started.

### ISSUE THREAD

**Issue by Pawanjit** [IndigoSlam/4_GIT_ABOUT_IT#21]
![image](https://cloud.githubusercontent.com/assets/8052753/15371399/118eec42-1cf0-11e6-8209-b11477333a64.png)

![image](https://cloud.githubusercontent.com/assets/8052753/15371417/2e50a456-1cf0-11e6-9551-65397e97bbbb.png)

**Comment by Pawanjit** [comment]
FIxed the issue. Pull number 23

**Comment by briankidd9design** [comment]
Pawanjit,
It looks like you did see the error I saw?
BK

**Comment by briankidd9design** [comment]
The game now is works as there is not back to list button. The user must complete the game before the his or her results are shown
